runtime: python38

handlers:

  - url: /purpleair_cache.data.json
    secure: always
    redirect_http_response_code: 301
    script: auto

  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: always

  - url: /
    static_dir: public
    secure: always

